cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jasminezhou:
      email: xxxx@gmail.com
      failed_login_attempts: 0
      first_name: Jasmine
      last_name: Zhou
      logged_in: false
      password: $2b$12$gfb2bbMu4VRzw/CGrC9kLOfI/Uy8MG3kDYK6K0TnLbNzARHJfsRlO
    reeseyang:
      email: xxx@gmail.com
      failed_login_attempts: 0
      first_name: Reese
      last_name: Yang
      logged_in: false
      password: $2b$12$4XgGtBQTmleOYKKd0gGrVe5zZlcp0GcK4y4MFqluCJ5UN5/ggKeam
pre-authorized:
  emails:
    - melsby@gmail.com
